### ISSUE TITLE
Exception in "Copying TWiLightMenu files" step

### ISSUE THREAD

**Issue by sergiofenoll** [mondul/HiyaCFW-Helper#11]
Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./HiyaCFW_Helper.py", line 828, in install_twilight
    move('_nds', path.join(self.sd_path, '_nds'))
  File "/usr/lib64/python2.7/shutil.py", line 313, in move
    copytree(src, real_dst, symlinks=True)
  File "/usr/lib64/python2.7/shutil.py", line 222, in copytree
    raise Error, errors
Error: [('_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\xa0bak.bmp', '/run/media/sff/3.9GBVolume/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\xa0bak.bmp', "[Errno 22] invalid mode ('wb') or filename: '/run/media/sff/3.9GBVolume/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\\xa0bak.bmp'")]
```

Running on Linux (Fedora, if it matters)

**Comment by mondul** [comment]
Seems that your system's Python doesn't have proper Unicode support. Will check with @RocketRobz if decoding that filename string has an impact on that theme.

**Comment by mondul** [comment]
Apparently decoding the string might break the AKMenu theme, so I need you to test that for me. Please go to line 828 and add .decode('utf-8') to the first parameter. The helper should work with that addition. After inserting the SD in your DSi please use the theme and let us know if it works OK

**Comment by mondul** [comment]
@sergiofenoll Added new release with bugfix.

**Comment by sergiofenoll** [comment]
Sorry for not helping, I didn't get any mails from GitHub so I didn't see your reactions. Thanks for the bugfix though.

**Comment by sergiofenoll** [comment]
@mondul I downloaded the hotfix and tried it again, got a different error this time (still related to string encoding)

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./HiyaCFW_Helper.py", line 819, in install_twilight
    move('_nds'.decode('utf-8'), path.join(self.sd_path, '_nds'))
  File "/usr/lib/python2.7/shutil.py", line 313, in move
    copytree(src, real_dst, symlinks=True)
  File "/usr/lib/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib/python2.7/shutil.py", line 203, in copytree
    copytree(srcname, dstname, symlinks, ignore)
  File "/usr/lib/python2.7/shutil.py", line 196, in copytree
    srcname = os.path.join(src, name)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 14: ordinal not in range(128)
```

**Comment by mondul** [comment]
@sergiofenoll Please get the latest .py from the repo (not from the releases) and test again.

**Comment by sergiofenoll** [comment]
Got the following error:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./HiyaCFW_Helper.py", line 820, in install_twilight
    path.join(self.sd_path, '_nds'))
  File "/usr/lib64/python2.7/shutil.py", line 313, in move
    copytree(src, real_dst, symlinks=True)
  File "/usr/lib64/python2.7/shutil.py", line 222, in copytree
    raise Error, errors
Error: [('_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\xa0bak.bmp', '/run/media/sff/3.9GBVolume/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\xa0bak.bmp', "[Errno 22] invalid mode ('wb') or filename: '/run/media/sff/3.9GBVolume/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\\xa0bak.bmp'")]
```
I'll go ahead and add the `encode(getfilesystemencoding() or getdefaultencoding())` to all the strings in `install_twilight()` and try it again. Is string encoding always such a big issue with python2 or is my system broken? I've never had these kinds of issues while working with python3.

**Comment by sergiofenoll** [comment]
```python
self.sd_path = self.sd_path.encode(getfilesystemencoding() or getdefaultencoding())
move('_nds'.encode(getfilesystemencoding() or getdefaultencoding()),
        path.join(self.sd_path, '_nds'.encode(getfilesystemencoding() or getdefaultencoding())))
```
Tried to do this, just as a test, got the same error message as before.

**Comment by mondul** [comment]
Python2 is ascii-based so has problems with unicode strings. Please use the unmodified .py from the repo, I tested it on a osboxes.org Fedora 28 machine and it worked
