### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by PwnBoi79** [mondul/HiyaCFW-Helper#112]
I am running linux mint and have downloaded the requirements for the tool, but when I run HiyaCFW_Helper.py i get this error
Traceback (most recent call last):
  File "./HiyaCFW_Helper.py", line 8, in <module>
    from tkinter import (Tk, Frame, LabelFrame, PhotoImage, Button, Entry, Checkbutton, Radiobutton,
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by PwnBoi79** [comment]
https://stackoverflow.com/questions/26357567/cannot-import-tkinter-after-installing-python-3-with-pyenv
