### ISSUE TITLE
Error when Copying TWiLightMenu files...

### ISSUE THREAD

**Issue by bluekeys** [mondul/HiyaCFW-Helper#35]
Exception in thread Thread-14:                                   
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '_nds' -> '/media/bluekeys/HOMEBREW/_nds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./HiyaCFW_Helper.py", line 849, in install_twilight
    move('_nds', path.join(self.sd_path, '_nds'))
  File "/usr/lib/python3.6/shutil.py", line 555, in move
    symlinks=True)
  File "/usr/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp', '/media/bluekeys/HOMEBREW/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp', "[Errno 22] Invalid argument: '/media/bluekeys/HOMEBREW/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\\udca0bak.bmp'")]

**Comment by spyjoshx** [comment]
Same deal here. I honestly have no idea what happened.

**Comment by spyjoshx** [comment]
I tried doing it on the same drive as my HiyaCFW helper installation, and it worked.

**Comment by bluekeys** [comment]
How strange... I'll try again a few different ways. Perhaps it's a python versioning thing?
