### ISSUE TITLE
Freeze in "Copying TWiLight Menu" (Python-Linux)

### ISSUE THREAD

**Issue by Ntemis** [mondul/HiyaCFW-Helper#46]
Exception in thread Thread-14:                                      
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '_nds' -> '/media/demetris/DSi/_nds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./HiyaCFW_Helper.py", line 873, in install_twilight
    move('_nds', path.join(self.sd_path, '_nds'))
  File "/usr/lib/python3.6/shutil.py", line 555, in move
    symlinks=True)
  File "/usr/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp', '/media/demetris/DSi/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp', "[Errno 22] Invalid argument: '/media/demetris/DSi/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\\udca0bak.bmp'")]

**Comment by mondul** [comment]
You have to update python

**Comment by mondul** [comment]
@Ntemis Please try again with the latest release

**Comment by Ntemis** [comment]
Sure, thanks

**Comment by ponnek** [comment]
I am receiving a similar error (but not the same) on the same file: Errno 22

Exception in thread Thread-8:                                   
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
OSError: [Errno 22] Invalid argument: '/media/ponnek/076B-D126/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./HiyaCFW_Helper.py", line 719, in install_twilight
    copy_tree('_nds', path.join(self.sd_path, '_nds'))
  File "/usr/lib/python3.7/distutils/dir_util.py", line 172, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python3.7/distutils/dir_util.py", line 172, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python3.7/distutils/dir_util.py", line 172, in copy_tree
    verbose=verbose, dry_run=dry_run))
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.7/distutils/dir_util.py", line 176, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/lib/python3.7/distutils/file_util.py", line 44, in _copy_file_contents
    "could not create '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not create '/media/ponnek/076B-D126/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp': Invalid argument


I tried copying the folder manually for the hell of it and received this error:

Error while copying "clock_numbers�bak.bmp (invalid encoding)".

OS is Ubuntu Budgie 19.04
