### ISSUE TITLE
Error not a directory

### ISSUE THREAD

**Issue by SomeGuy290** [mondul/HiyaCFW-Helper#58]
so I was installing HiyaCWF but it would not complete as it said "distutils.error.DistutilsFileError: cannot copy tree 'DSi - CFW users\SDNADA root' : not a directory". If there are any solutions I am willing to try them out. I have also tried installing the program more then once.

**Comment by SpikeSP87** [comment]
Some additional info about this error:

Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\Downloads\dsi\HiyaCFW-Helper-v3.4-Python3\HiyaCFW_Helper.py", line 718, in install_twilight
    copy_tree(path.join('DSi - CFW users', 'SDNAND root'), self.sd_path, update=1)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\distutils\dir_util.py", line 124, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree 'DSi - CFW users\SDNAND root': not a directory

**Comment by imacross001** [comment]
im having the same issue... i tried to do what @SpikeSP87 said but the error still remains... can you please explain better :)

**Comment by imacross001** [comment]
Exception in thread Thread-12:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "HiyaCFW_Helper.py", line 718, in install_twilight
  File "distutils\dir_util.py", line 124, in copy_tree
distutils.errors.DistutilsFileError: cannot copy tree 'DSi - CFW users\SDNAND root': not a directory

**Comment by SomeGuy290** [comment]
So if I am understanding correctly @SpikeSP87 all I have to do is install hiyaCFW without twilight menu then add twilight menu later? If so where can I download the twilight menu separately?

**Comment by imacross001** [comment]
yes @SomeGuy290 i tried it and it worked, heres the link, the instructions are there too
https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/

**Comment by mondul** [comment]
Fixed in 116f430301e1177d0804f50801c392206a954afb

**Comment by SomeGuy290** [comment]
Thanks @SpikeSP87 and @imacross001. Everything is working great after I installed both hiyaCFW and Twilight menu separately. Now time to have some fun with roms. :)
